### ISSUE TITLE
Fix Padding / Improve Responsiveness

### ISSUE THREAD

**Issue by EdgeKing810** [EdgeKing810/Entities#1]
When a hero / villain is about to be deleted (after the delete button is pressed), the following menu comes up. The padding, especially at the bottom needs to be fixed and it should look better on different screen sizes.

![image](https://user-images.githubusercontent.com/42406341/94335612-cc693380-ffed-11ea-8105-ceaa39dec26d.png)

**Comment by pranavvp10** [comment]
Hi @EdgeKing810  can i work on this issue?.

**Comment by greyGroot** [comment]
can i work on it?

**Comment by EdgeKing810** [comment]
@greyGroot sure, first come work on it. However, don't submit a pull request before October.

**Comment by sushabhardy** [comment]
@EdgeKing810 Please assign the issue to respective person once finalized, so that others get to know that issue is already taken.

**Comment by sleepinzombie** [comment]
Can you assign me this please? @EdgeKing810

**Comment by greyGroot** [comment]
I'm working on it, but I'm having problems with lunching project on my local machine. If I won't be able to solve, I will resign.

**Comment by greyGroot** [comment]
@EdgeKing810 please assign this issue to @sleepinzombie

**Comment by EdgeKing810** [comment]
Okay, thanks for letting me know @greyGroot

**Comment by sleepinzombie** [comment]
@EdgeKing810 Thank you for assigning to me. Will be working on it.
