### ISSUE TITLE
Add a section for Disney Characters

### ISSUE THREAD

**Issue by EdgeKing810** [EdgeKing810/Entities#3]
Same as #2 but for Disney Characters.

**Comment by GauravPandey1898** [comment]
i can help you out.

**Comment by EdgeKing810** [comment]
Do you want to work on this @GauravPandey1898?

**Comment by GauravPandey1898** [comment]
Yes, give me more detail about this issue.

**Comment by EdgeKing810** [comment]
Do you have any questions in particular regarding this @GauravPandey1898 ? Check out https://heroes.kinesis.games for a demo and inspect the code.
