### ISSUE TITLE
Fix villain category - The Green Goblin

### ISSUE THREAD

**Issue by EdgeKing810** [EdgeKing810/Entities#6]
In the `initial-data.json` file, the last villain has an invalid category.

```
{
    "id": "villain-4",
    "name": "The Green Goblin",
    "tagline": "Why Bother?",
    "category": "heroes"
  }
```

**Comment by sleepinzombie** [comment]
@EdgeKing810 Can you please assign this to me please?

**Comment by sleepinzombie** [comment]
@EdgeKing810 Thank you for the merge! Good to close?
